### Goldsmiths University of London
### Author....: Carlos Manuel de Oliveira Alves
### Student...: cdeol003
### Created...: 23/01/2023
### Lab No....: 2

## Task a)
#### Generate a 2 dimensional array of numbers of shape (10,10),containing all the numbers from 0 to 99, and convert them to float (Hint: add 0.0 to the array of integers).

In [3]:
# Import numpy library
import numpy as np

# create a 2D array with shape (10, 10) containing all the numbers from 0 to 99
two_d_array = np.arange(100).reshape(10, 10)

# print the 2D array created above
print(two_d_array)

# convert the 2D array into a float array
two_d_array = two_d_array.astype(np.float)

# print the 2D array created above
print(two_d_array)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]


C:\Users\Carlos Alves\AppData\Local\Temp\ipykernel_28296\2754463953.py:11: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  two_d_array = two_d_array.astype(np.float)


## Task b)
#### Print the 2nd column.

In [4]:
# print the 2nd column of the 2D array
print(two_d_array[:, 1])

[ 1. 11. 21. 31. 41. 51. 61. 71. 81. 91.]
